### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by forsomefun2** [dchang0/torrentwatch-xa#10]
How do you update the program without having to go through all the steps again
I am trying the .sh install script but it keeps saying Cannot find new torrentwatch-xa lib tree to install; exiting.

**Comment by dchang0** [comment]
Hmm. You should not be getting that error if you downloaded the newest version as a ZIP or tar.gz file and unzipped it all in one place. The install_twxa.sh uses relative paths to get the folders it is going to install.

For instance, the lines that are giving you trouble are:

```
# make sure new torrentwatch-xa package is accessible
if [ ! -e var/lib/torrentwatch-xa/lib/twxa_tools.php ]
then
    echo "Cannot find new torrentwatch-xa lib tree to install; exiting."
    exit
fi
```

All that does is check to see if var/lib/torrentwatch-xa/lib/twxa_tools.php exists. It exits if it doesn't and continues if it does.

What that suggests is that you don't have the whole installation ZIP or tar.gz OR the install_twxa.sh file is in the wrong folder relative to the unzipped files.

**Comment by forsomefun2** [comment]
I'm not sure I downloading the zip
instead of using the download command from install.md 

does it work when you try it now?

**Comment by dchang0** [comment]
Just tested the install_twxa.sh script after getting a fresh copy of the files using:

`git clone https://github.com/dchang0/torrentwatch-xa.git`

It worked and upgraded the installation I had.

BTW, you are correct: if you use the git command, then you bypass the ZIP and tar.gz files (git compresses the files for transfer and automatically uncompresses them when they arrive).

**Comment by forsomefun2** [comment]
yeah then

/root/torrentwatch-xa/install_twxa.sh --keep-config

**Comment by dchang0** [comment]
Oh!
Try this:

```
cd /root/torrentwatch-xa
./install_twxa.sh
```

That should work. Relative paths is the problem here.

**Comment by forsomefun2** [comment]
shoot did that delete the config file

**Comment by dchang0** [comment]
Ah crap, yeah, I left off the --keep-config. Sorry about that!

**Comment by dchang0** [comment]
Hmm. How to recover... You might have a backup config file from an earlier upgrade, although it may be too old. Check your home folder.

**Comment by dchang0** [comment]
If you don't have a backup of the config file, well, there were a lot of changes to the config made in the last few versions, so it might be good to start fresh anyway.

Then, to quickly add your Favorites in bulk, use the new twxa_fav_import.php (see USAGE.md for instructions) to add them all back.

**Comment by dchang0** [comment]
Based on this mistake, I think I'll change the default behavior of the script so it always keeps the config file, just in case. Sorry about that.

**Comment by forsomefun2** [comment]
I have a backup not sure where to put it

**Comment by forsomefun2** [comment]
I got it fixed thank you

**Comment by dchang0** [comment]
Whew, good save!

I’ll definitely improve the script and documentation so this doesn’t happen again.

**Comment by dchang0** [comment]
Just realized that the script already backs up the file regardless of whether --keep-config is specified or not, so I guess this was addressed a while ago. I'll update the documentation to address the relative paths problem. Thanks for reporting this!
