### ISSUE TITLE
Add destination path to the favorites data. 

### ISSUE THREAD

**Issue by thawkins** [dchang0/torrentwatch-xa#12]
Allow specification of a destination path and pattern to  the favorites database, so that matched shows can be moved directly to an archive for that specific show. 

Ie 

/tvarch/shows/{show}/Season {season}/

**Comment by dchang0** [comment]
Hi, thawkins--

This feature might already exist in two parts:

1) Specify a base path for one Favorite by using the Download Dir fields in the Favorite. (The filesystem path you specify must be accessible by the transmission-daemon.)

2) Turn on the Deep Directories feature by choosing Show Title and Season.

I am not sure if this will actually work. so I have to test it myself. Give it a try and see if it does work for you.

**Comment by dchang0** [comment]
Good. I just confirmed that yes, this feature already exists and works as you would like.

Do the steps in the above post, and it will automatically combine Deep Directories with per-Favorite Download Dir.

**Comment by thawkins** [comment]
i will give this a try

**Comment by dchang0** [comment]
It'll work. I've been testing it since you opened the ticket, and it works great. Let me know if you have any trouble with it.

**Comment by thawkins** [comment]
thanks, i have the day off tomorrow so i will set it up and try it, im fed
up having to move all the episodes into the correct folders for plex.

**Comment by dchang0** [comment]
Cool. Another tip: use absolute paths to bypass potential problems.
For instance, on my QNAP NAS running transmission-daemon, the normal download path is:

/share/Download/transmission/completed

And then I used this path for the one show I used for testing this feature:

/share/Download/transmission/completed/test

(Both paths are read & write for transmission-daemon's user.)

The shows get put into this absolute path by the Deep Dirs feature:

/share/Download/transmission/completed/test/{show}/Season {season}
