### ISSUE TITLE
Cannot move active downloads to new location

### ISSUE THREAD

**Issue by efelon** [dchang0/torrentwatch-xa#13]
When I try to move a download (running or finished)...
![Bildschirmfoto von 2021-02-20 23-40-26](https://user-images.githubusercontent.com/10722552/108610323-1efc1f80-73d5-11eb-853a-41a0dd130c0f.png)
...nothing happens when I press enter or when I press the "Move" button.

I get the following error in the browser console:

```
Uncaught ReferenceError: assignment to undeclared variable path
    moveTorrent https://mydomain.com/torrentwatch-xa/javascript/torrentwatch-xa.js:1507
    processSelected https://mydomain.com/torrentwatch-xa/javascript/torrentwatch-xa.js:1663
    onclick https://mydomain.com/torrentwatch-xa/#:1
    jQuery 5
    <anonymous> https://mydomain.com/torrentwatch-xa/javascript/twxa_event_bindings.js:83
    jQuery 8
    <anonymous> https://mydomain.com/torrentwatch-xa/javascript/twxa_event_bindings.js:67
    jQuery 13
torrentwatch-xa.js:1507:16

```
I'm on latest git master.

If it is not a general problem, it would be great to get a direction where I can look at.

Regards,
efelon

**Comment by dchang0** [comment]
Thanks--I will take a look at it and try to reproduce it.

A few things you can check:

1) Does the path exist? (I figure it does, but it doesn't hurt to ask.)
2) Does the web server user account have write permissions to that path?
3) Does the transmission-daemon user account have write permissions to that path?
4) Do you have SELINUX turned on? Could you turn it off temporarily and try it again?
5) Were or are you able to move the torrent to any other path on the same server?

Thanks!

**Comment by dchang0** [comment]
I think I may have found the bug.

In the file torrentwatch-xa.js, take a look at line 1507.

It should look like this:

path = $('input#moveTo')[0].value;

Please change it to this:

path = $('#moveTo').val();

Then, test it and let me know how it works. It should work. I am pretty sure this is a bug I introduced while trying to switch from jQuery to regular old Javascript, and then I switched back to jQuery.

If it works, then I will make the change to the source code, commit, and push it.  

Thanks!

**Comment by dchang0** [comment]
Turns out there is another problem.
The `'use strict';` on line 1506 is causing the error.

Remove that line and it will work with

path = $('#moveTo').val();

OR you can add var to the front of the new line 1507 like so:

`var path= $('#moveTo').val();`

I was adding 'use strict'; as part of my cleanup of the code. It would eventually be removed. But adding var is proper, so my recommendation is to change line 1507 to:

`var path = $('#moveTo').val();`

**Comment by efelon** [comment]
> so my recommendation is to change line 1507 to:
> 
> var path = $('#moveTo').val();
> 
> and also remove line 1506.

@dchang0 I confirm that this fixed my problem. Thanks.

**Comment by dchang0** [comment]
Thanks for confirming that it worked and thanks for reporting the bug!
