### ISSUE TITLE
18.04

### ISSUE THREAD

**Issue by forsomefun** [dchang0/torrentwatch-xa#3]
Think something broke the program with the update

$v) { unset($process[$key][$k]); if (is_array($v)) { $process[$key][stripslashes($k)] = $v; $process[] = &$process[$key][stripslashes($k)]; } else { $process[$key][stripslashes($k)] = stripslashes($v); } } } unset($process); } // parses commands sent from web UI (usually torrentwatch-xa.js) function parse_options($twxa_version) { global $html_out, $config_values; array_keys($_GET); $commands = array_keys($_GET); if (empty($commands)) { return false; } if (strpos($commands[0], '/') === 0) { $commands[0] = preg_replace("/^\//", '', $commands[0]); } switch ($commands[0]) { case 'getClientData': echo getClientData(); exit; case 'delTorrent': if (isset($_REQUEST['trash'])) { if (isset($_REQUEST['checkCache'])) { $response = delTorrent($_REQUEST['delTorrent'], $_REQUEST['trash'], $_REQUEST['checkCache']); } else { $response = delTorrent($_REQUEST['delTorrent'], $_REQUEST['trash'], false); } } else { if (isset($_REQUEST['checkCache'])) { $response = delTorrent($_REQUEST['delTorrent'], false, $_REQUEST['checkCache']); } else { $response = delTorrent($_REQUEST['delTorrent'], false, false); } } echo "$response"; exit; case 'stopTorrent': echo stopTorrent($_REQUEST['stopTorrent']); exit; case 'startTorrent': echo startTorrent($_REQUEST['startTorrent']); exit; case 'moveTo': echo moveTorrent($_REQUEST['moveTo'], $_REQUEST['torHash']); exit; case 'updateFavorite': $response = update_favorite(); if (strpos($response, 'Error:') === 0) { echo "
$response
"; } break; case 'updateFeed': updateFeed(); break; case 'clearCache': clear_cache_by_cache_type(); break; case 'setGlobals': updateGlobalConfig(); break; case 'addFavorite': $feedLink = $_GET['rss']; foreach ($config_values['Feeds'] as $key => $feed) { if ($feed['Link'] == "$feedLink") { $idx = $key; } } if (($tmp = detectMatch(html_entity_decode($_GET['title'])))) { $_GET['name'] = trim(strtr($tmp['favTitle'], "._", " ")); switch ($config_values['Settings']['Match Style']) { case "simple": $_GET['filter'] = trim($tmp['favTitle']); $_GET['quality'] = $tmp['qualities']; // Add to Favorites uses the qualities from the item for the new Favorite break; case "glob": $_GET['filter'] = trim(strtr($tmp['favTitle'], " ._", "???")); $_GET['filter'] .= '*'; $_GET['quality'] = 'All'; // Add to Favorites makes the new Favorite accept all qualities break; case "regexp": $_GET['filter'] = trim($tmp['favTitle']); $_GET['quality'] = $tmp['qualitiesRegEx']; // Add to Favorites uses the detected qualities as a regex or .* if no qualities detected } $_GET['feed'] = $_GET['rss']; $_GET['button'] = 'Add'; $_GET['downloaddir'] = 'Default'; $_GET['alsosavedir'] = 'Default'; $_GET['seedratio'] = ""; } else { $_GET['name'] = $_GET['title']; $_GET['filter'] = $_GET['title']; $_GET['quality'] = 'All'; $_GET['feed'] = $_GET['rss']; $_GET['button'] = 'Add'; $_GET['downloaddir'] = 'Default'; $_GET['alsosavedir'] = 'Default'; $_GET['seedratio'] = ""; } if ($config_values['Settings']['Default Feed All'] && $tmp['numberSequence'] > 0) { // set default feed to all only if serialized $_GET['feed'] = 'All'; } $response = update_favorite(); if ($response) { echo "$response"; } exit; case 'hide': /* $response = add_hidden(ucwords($_GET['hide'])); if ($response) { echo "ERROR:$response"; } else { $guess = detectMatch(html_entity_decode($_GET['hide'])); echo $guess['favTitle']; // use favTitle, not title } */ addHidden($_GET['hide']); exit; case 'delHidden': if (!empty($_GET['unhide'])) { delHidden($_GET['unhide']); // filter_input() will fail here because $_GET['unhide'] is an array } break; case 'dlTorrent': // Loaded via ajax foreach ($config_values['Favorites'] as $fav) { $guess = detectMatch(html_entity_decode($_GET['title'])); $name = trim(strtr($guess['title'], "._", " ")); if ($name == $fav['Name']) { $downloadDir = $fav['Download Dir']; } } if ((!isset($downloadDir) || $downloadDir == "Default" ) && isset($config_values['Settings']['Download Dir'])) { $downloadDir = $config_values['Settings']['Download Dir']; } $r = client_add_torrent(str_replace('/ /', '%20', trim($_GET['link'])), $downloadDir, $_GET['title'], $_GET['feed']); if ($r == "Success") { //$torHash = get_torHash(add_cache($_GET['title'])); $torHash = get_torHash(add_cache(filter_input(INPUT_GET, 'title'))); } if (isset($torHash)) { echo $torHash; } else { echo $r; } exit(0); break; case 'clearHistory': // Loaded via ajax if (file_exists($config_values['Settings']['History'])) { unlink($config_values['Settings']['History']); } display_history(); close_html(); exit(0); break; case 'get_client': global $config_values; echo $config_values['Settings']['Client']; exit; case 'get_autodel': global $config_values; echo $config_values['Settings']['Auto-Del Seeded Torrents']; exit; case 'getDisableHideList': global $config_values; echo $config_values['Settings']['Disable Hide List']; exit; case 'checkVersion': echo checkVersion($twxa_version); exit; case 'get_dialog_data': //switch ($_GET['get_dialog_data']) { switch (filter_input(INPUT_GET, 'get_dialog_data')) { case '#favorites': display_favorites(); exit; case '#configuration': display_global_config(); exit; case '#hidelist': display_hidelist(); exit; case '#feeds': display_feeds(); exit; case '#history': display_history(); exit; case '#show_legend': display_legend(); exit; case '#clear_cache': display_clearCache(); exit; case '#show_transmission': display_transmission(); exit; default: exit; } default: //TODO check filter_input() is not false before using it $output = ""; } if (isset($output)) { if (is_array($output)) { $output = implode("
", $output); } $html_out .= str_replace("\n", "
", "
$output

**Comment by dchang0** [comment]
Thanks for reporting this.
I have a few questions for you:
1) Were you running torrentwatch-xa on Ubuntu 18.04 successfully before, and then some update to 18.04 broke it just now?
2) What version of PHP are you currently at (after it broke)?
3) Are you on amd64/x86_64 or ARM architecture?

Thanks.

**Comment by forsomefun** [comment]
1. No I just updated
2.This is what is says when I am on php is already the newest version (1:7.2+60ubuntu1). None of the packages had updates when I tried to reinstall 
3. I am on AMD64.

I think the issue is with Desktops some how.
1. Tried on my mobile phone works, and gets to the site
2. Tried on Main Computer Fails
3. Tried on Secondary Computer Fails
4. Tried Unused Computer Web Browser Fails
( All on the same network)

**Comment by dchang0** [comment]
Oh, that's interesting and also tough to diagnose. It might be a browser-side problem, maybe a Javascript error. Do you see any errors in the web browser's javascript console? There probably are a pile of errors.

**Comment by forsomefun** [comment]
I went to Developer tools
Consoles

This is the only thing that shows up
Uncaught SyntaxError: missing ) after argument list
    at p (jquery-3.2.1.min.js:2)
    at Ja (jquery-3.2.1.min.js:3)
    at r.fn.init.append (jquery-3.2.1.min.js:3)
    at r.fn.init.r.fn.(/torrentwatch-xa/anonymous function) [as appendTo] (http://91.134.116.36/torrentwatch-xa/javascript/jquery-3.2.1.min.js:3:18644)
    at torrentwatch-xa.js:1043
%22:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by dchang0** [comment]
Thanks. That's pretty helpful. It is likely that the server is truncating some Javascript sent to the browser. No idea why. I'll build a testbed to match your setup and try to replicate the error.

**Comment by dchang0** [comment]
How did you get past the problem of php-mbstring being missing from the official Ubuntu 18.04 repositories?

**Comment by dchang0** [comment]
Okay, I just did a clean install of Ubuntu Server 18.04 from the ISO right now, and there are no errors in the web browser console nor in /var/log/apache2/error.log.

I'll run an apt-get upgrade now and see if the error occurs.

**Comment by dchang0** [comment]
Hmm. There are no packages for me to upgrade (I have the latest packages). So I am unable to reproduce the error you are seeing with a fresh install of Ubuntu Server 18.04 with the latest packages.

I installed all the same packages as was specified for Ubuntu 16.04.

Are you in a position to test a separate, fresh install of Ubuntu Server 18.04? (For instance, do you have virtual machines you can use for testing?)

**Comment by forsomefun** [comment]
I'll try to reinstall it first.

**Comment by dchang0** [comment]
Thanks. Another question: are you using Apache2.x or Nginx?

**Comment by forsomefun** [comment]
apache2.x I am following the instructions from your post. So it whatever you have people download

**Comment by forsomefun** [comment]
I found a config file but I am not sure if it is correct. Location.
/torrentwatch.../.git/config

**Comment by dchang0** [comment]
That's not the right one. Look for: /var/lib/torrentwatch-xa/config_cache/torrentwatch-xa.config
Copy that somewhere else, then destroy both it and the other file: /var/lib/torrentwatch-xa/config_cache/torrentwatch-xa-config.cache

When you open torrentwatch-xa in a browser or the cron job runs it, it will automatically generate a new config file that is blank.

**Comment by forsomefun** [comment]
search for all folders name 'torrentwatch-xa 
sudo apt-get remove apache2 php php-mbstring php-curl libapache2-mod-php transmission-daemon git

The issue still exist
I will try another VPS to see what happens

**Comment by dchang0** [comment]
Does the VPS OS have a lot of customizations? I'm using an Ubuntu 18.04 ISO gotten directly from ubuntu.com. It's completely bone stock with nothing but the default repositories.

**Comment by dchang0** [comment]
Check to see if Hetzner Cloud customizes the php.ini or Apache2.x config files a lot. It might also be a firewall setting.

**Comment by forsomefun** [comment]
Thanks fo your help. I think the best thing would be to reset the VPS, and try again with a fresh install. 

I got it working on my testbed.  So something must have failed in my first upgrade attempt

**Comment by dchang0** [comment]
Glad to help--thanks!
