### ISSUE TITLE
Is there a way to stop full seasons to be downloaded?

### ISSUE THREAD

**Issue by efelon** [dchang0/torrentwatch-xa#4]
Hi,

I'm on 1.0.0 from the release tags. Recently in my feeds some full season torrents show up like:

> ExampleName S02 WEBRip

In this case it was a fake coming up before the full season actually was aired, stopping further downloads. Ending up setting the favorite to:

![image](https://user-images.githubusercontent.com/10722552/42160230-b3e7c608-7df6-11e8-9797-93e008d43000.png)

**Another case:**

Although a series favorite already states last downloaded e.g. 6x10, upcoming full seasons like S02 are downloaded regardless of the current progress of the series.

It would be really helpful to disable "full" season downloads by setting.

In general i'm very happy with the software and also successfully updated to 1.0.0 with your script.

Best regards,
Martin

**Comment by dchang0** [comment]
Thanks for the screenshot.

You can stop torrentwatch-xa from downloading full seasons by going into the Configuration > Favorites and checking **Ignore Batches**. A full season is a large batch, basically. The smallest batches are two episodes; some of the fansub crews release episodes in pairs. Most people do not need to download batches of any size because they expect to get one episode at a time, so checking this box usually makes no difference to them.

To reset the Favorite, clear the two Last Downloaded textboxes from the Favorite and save the Favorite, then empty the Torrents Cache. It will then pick up the next episode it sees, which might be the current episode if it is still in the feed.

**Comment by efelon** [comment]
I didn't realize that batch could mean that, so thanks for the explanation. I'm not aware I have touched these settings since first installation. So, full of hope I went there and:

![image](https://user-images.githubusercontent.com/10722552/42187253-aba3f1fc-7e4f-11e8-9a06-4edb7f3554c3.png)

As you can see this option was already enabled while these incidents happened. The latest case was an episode containing "S02E12-E13", which should also be ignored if I understood what you said correctly.

**Comment by dchang0** [comment]
Ah yes, if it did catch that while you had Ignore Batches checked, then getting a full season is indeed a bug. I am reopening the case.

S02E12-E13 MIGHT not be detected by my engine. I don't remember ever writing a pattern match for that syntax. I'll test it and see what happens, whether it is treated as a single episode or as a batch of two episodes.

Thanks!

**Comment by dchang0** [comment]
Hi, Martin--
The logic for Ignore Batch looks fine so far. Could I ask you to copy and paste the portion of the log /tmp/twxalog where it decided to download the batches?
Hopefully you have the log set to Debug level, which would explain exactly why it thought the batch was worth downloading in spite of Ignore Batches being checked.
If you don't have the log, oh well. We'll both try to trigger the problem again. Part of the problem is that we have to wait until a fake full season or a real batch comes through a feed.
Thanks very much!

**Comment by dchang0** [comment]
So far, I am unable to reproduce the problem by adding Favorites for batches currently visible in my feed such as "HorribleSubs Megalo Box 1-13 Unofficial Batch 480p"  which is detected as 1x1-1x13
If Ignore Batches is checked, it shows up as Violet (Ignored Favorite Batch) and does not download.

**Comment by efelon** [comment]
I'm very sorry. I don't have the log level on debug and also can not reproduce it a second time. When it happened I was busy and had no time looking into it.

If you want quicker reproduction you can look at limetorrents. They provide a RSS for custom searches even though the links within this feed don't work anymore. But for testing matches it works ok.

**Comment by dchang0** [comment]
LimeTorrents, huh? I'll check it out. Hopefully we can reproduce this soon. Thanks!

**Comment by efelon** [comment]
It happened again this night. Although I haven't enable debug log in the config file yet, I post the lines of the log anyway:

> 2018-07-06T03:30:15+02:00 DBG: Started processing 1 feed: YourBittorrent RSS - Television
> 2018-07-06T03:30:15+02:00 DBG: Match found for xxxxxx.S02.WEBRip.XviD.IdeaFilm
> 2018-07-06T03:30:18+02:00 INF: Started: xxxxxx.S02.WEBRip.XviD.IdeaFilm in /var/download
> 2018-07-06T03:30:18+02:00 DBG: Removing config cache: /var/lib/torrentwatch-xa/config_cache/torrentwatch-xa-config.cache
> 2018-07-06T03:30:18+02:00 DBG: Successfully wrote config file: /var/lib/torrentwatch-xa/config_cache/torrentwatch-xa.config
> 2018-07-06T03:30:18+02:00 DBG: Updated Favorite: xxxxxx.S02.WEBRip.XviD.IdeaFilm
> 2018-07-06T03:30:18+02:00 INF: Exact in cache; ignoring: xxxxxx.S02.WEBRip.XviD.IdeaFilm
> 2018-07-06T03:30:18+02:00 INF: Processed 1 feed: YourBittorrent RSS - Television

**Comment by dchang0** [comment]
Thanks. From what I can tell, it is bypassing the batch logic and downloading it directly as a single item. If the item is still in your feed, could you turn on Configure > Interface > Show Item Debug Info and then tell me what it says at the right side of the item. It should say 2XFULL, but if it says something different, then that is probably the cause.

**Comment by efelon** [comment]
Unfortunately it is not any more. I tried the limetorrents search and got not that exact name as the one causing the trigger:

> "xxxxxx.S02.WEBRip.XviD.IdeaFilm"  <- seams to trigger (what caused the log above)
> "xxxxxx S02 WEBRip XviD IdeaFilm"   <- doesn't seam to trigger (debug: 2xFULL)

What I find strange is, that some of the 2XFULL torrents are marked as "Previously Downloaded", although I cleared all the caches. And not as "Ignored Favorite Batch" or "Old Favorite".

Can you point me to how i need to enable debug output, this would save me some time to look it up. ;)
I'll provide the debug log again next time.

Thanks for your patience.

**Comment by dchang0** [comment]
If you are running 1.1.0, turning on Debug Log Level is super-easy. Go to Configure > Interface > Log Level and set it to DEBUG. Also, please check the box Configure > Interface > Show Item Debug.

I am not exactly able to reproduce the problem but got close with the show "GLOW.S02.720p.ColdFilm" It detects as 2xFULL but downloaded anyway. Different from your situation, it did not update the Favorite to 2xFULL. Something weird is going on. I will need more data to debug it.

**Comment by dchang0** [comment]
BTW, Previously Downloaded will occur if the Favorite itself has been updated to 2xFULL. You need to remove the FULL part and put the last episode you successfully got.

**Comment by dchang0** [comment]
Hahaha! I might have found the bad logic just by reading the code line-by-line--there is a logical case where I don't check to see if Ignore Batches is turned off but it is supposed to check. Let me fix that and see if that fixes it.

**Comment by efelon** [comment]
I'm still on 1.0.0. so I think I find some time tonight to update to 1.1.0. and make what you suggested.

Oh, and I did reverse the favorite to 2x10. Regardless of that it shows some as "Previously Downloaded". 

Good to hear about your finding. I follow your change after you checked in.

**Comment by dchang0** [comment]
Hmm. There might be more than one bug if you reversed the Favorite and it says Previously Downloaded and you also emptied all caches. But for now, let's focus on fixing this one bug, then later if the Previously Downloaded bug happens, please create a new Issue for it. With debug logging and debug item info, we'll be able to pin it down quickly.

**Comment by dchang0** [comment]
Patch is up. I tested it using "GLOW.S02.720p.ColdFilm" and it is blocked if Ignore Batches is turned on. Please close the ticket if it works for you.

**Comment by dchang0** [comment]
I just realized that Previously Downloaded does not rely on the Favorite's Last Episode. It is entirely based on whether the item is seen in the cache.
If you emptied all the caches but Previously Downloaded items still show up, it is possible that the caches were not really emptied. Please use the command line and check the path /var/lib/torrentwatch-xa/dl_cache and see if there are files in there that start with `dl_` There should be none right after emptying all caches.

**Comment by efelon** [comment]
I updated my installation to 1.1.0 (master) and set logging to debug.
Let's give it some time to "feed".  ;)

**Comment by dchang0** [comment]
Sweet! Thanks for following-up on that.

Hmm. Ignore batches per Favorite is probably do-able. Let me add that to the TODO list.
