### ISSUE TITLE
Layout cluttering in feed configuration when list is too long

### ISSUE THREAD

**Issue by efelon** [dchang0/torrentwatch-xa#6]
As soon as the right scroll indicator gets visible the layout will be broken:

![image](https://user-images.githubusercontent.com/10722552/42217872-2272e4d8-7ec7-11e8-95ce-9f61d242dbca.png)

**Comment by dchang0** [comment]
Interesting! That should be very easy to fix.
What browser is that you're using? I'm guessing it's a LINUX-based browser, maybe Firefox or Chromium... The scrollbar is wider than I expected.

**Comment by dchang0** [comment]
This is fixed now in torrentwatch-xa.css. I turned on the scrollbar permanently and shifted the controls left to make room for it. Thanks for reporting it and posting a screenshot!

**Comment by dchang0** [comment]
BTW, if your browser still causes a line-wrap due to the width of its scrollbar, let me know. I'll shift the controls further left.

Also, you may have to refresh the browser to force it to load the new CSS file. Safari on the Mac is especially bad at this. Firefox and Chrome are generally good about re-loading CSS files.

**Comment by dchang0** [comment]
I might have to move the elements by an additional 5px due to the unusually wide scrollbar you have in your browser. Right now, it's set at 275px and all the browsers I have tested work, but they do not have a scrollbar as wide as yours. I think we might need to set it to 270px for yours to work.

**Comment by efelon** [comment]
Hi dchang0,

sorry I forgot to give you more information on my system.

OS: Linux Mint (I think 18.3)
Desktop: Mate
Browser: Chromium (latest on distribution; I can check the version back @ home if you need it)

It can take some days for me to find time to test it on my setup. Your reaction time instead is definitely unbeatable. ;)

**Comment by dchang0** [comment]
Cool, thanks. No need to get the version of Chromium--it probably has wide scrollbars no matter what version it is. I'll see if I have a VM with Linux Mint for testing. Thanks!
