### ISSUE TITLE
First two items of the collapsible lists can only be expanded in Firefox

### ISSUE THREAD

**Issue by efelon** [dchang0/torrentwatch-xa#8]
... after expansion they cannot be collapsed anymore.

Testing on Windows7
Firefox (60.0.1 (64-bit))
Chrome is working (Version 65.0.3325.181 (Offizieller Build) (64-Bit)) 
torrentwatch-xa (1.1.0 master)

**Comment by dchang0** [comment]
What do you mean by "first two items"? Do you mean the first two Feeds out of several feeds, or the first two individual torrent items in each Feed?

I'm guessing you mean the first two Feeds out of several Feeds. It's probably a JQuery bug.

**Comment by dchang0** [comment]
I'm not able to reproduce any problem expanding and collapsing the Feed headers, BUT I am using these versions:

Windows 10 Pro (not Windows 7) 1803, Build 17134.112
Firefox 61.0.1 64-bit (not 60.0.1 64-bit)

What happens if you upgrade Firefox from 60.0.1 to 61.0.1? If you can't do that for some reason, let me know. I don't have a Windows 7 testing box, so we'll have to use yours for debugging.

**Comment by efelon** [comment]
Yes, I mean the feed list header out of several. I have 8 and I can operate on the other 3 - 8 both operations of collapsing and expanding. Only the first two feed lists ignore pressing on the small arrows when I try to collapse them regardless of the selection ("All", "Matching", Downloading", ...). But, when I change between "All" and e.g. "Matching" and back to "All", they are collapsed again.

I just updated to 61.0.1 (64-bit) but the problem still persists for Firefox. I'm delivering the site with nginx and php7.0. But i assume this doesn't matter since chrome is working. Back @ home I can test chromium and Firefox on Linux.

**Comment by efelon** [comment]
Working correctly on 

- Linux Mint 18.3 with:
**Firefox** (61.0 Firefox for Linux Mint)
**Chromium** (Version 66.0.3359.181 (Official Build) Built on Ubuntu)

- Windows 10:
**Firefox** (60.0.2 32-bit)
**Chrome** (65.0.3325.181 64-Bit)

On Windows 7 within Firefox i quickly looked also into the developer console but couldn't see anything useful.

As you can see I can't reproduce on the other systems as well. In my opinion you may close this as less than minor.

**Comment by dchang0** [comment]
What a weird bug!
On your Windows 7 machine with the bug, please try deleting the cookies for the torrenwatch-xa server in Firefox. It might be a cookie bug and not a Javascript/JQuery bug.

**Comment by efelon** [comment]
Guess what... deleting cookies indeed resolved the issue.

Greetings

**Comment by dchang0** [comment]
Very cool--thanks for letting me know.
