### ISSUE TITLE
Torrent links within some feeds don't get recognized

### ISSUE THREAD

**Issue by efelon** [dchang0/torrentwatch-xa#9]
### Problem

I came across this problem some time ago with the old torrentwatch-x on qnapnas where links from - I think it was kickass torrents - were not identified. Those links looked like this for example:

> http://itorrents.org/torrent/42AEABA2CE6938C4C43F33FD609A9848FF4BB6F2.torrent?title=Drug-Lords-S02E02-WEB-x264-TVSLiCES

This is now also the case for limetorrents.cc (e.g. https://www.limetorrents.cc/rss/20/). They use the hash value as file name as you can see.

### Solution

At that time I made a quick fix which also works for you. I tested it on limetorrents and briefly for some other feeds, so that there is no impact. Since I'm not fluent with git and github (Pull requests) and the fix is very small I hope you don't mind me putting it in here as text:

> torrentwatch-xa/var/lib/torrentwatch-xa/lib/twxa_feed.php

New function:
```
/**
 * @brief Tries to extract a torrent hash from given URL constructs a magnet link from it
 * @param $url string
 * @return $url if no torrent SHA-1 hash string was found within $url
 * @return magnet-link containing extracted torrent hash
 */
function magnetlink_getMagnetLinkFromURL($url)
{
	$hash = preg_replace('/.*([a-fA-F0-9]{40}).*/', '$1', $url);
	if ($hash === $url)
	{
		return $url;
	}
	else
	{
		return "magnet:?xt=urn:btih:$hash";
	}
}

```

Changed function :

```
function get_torrent_link($rs) {
  $links = array();
  $link = "";
  if ((isset($rs['enclosure'])) && ($rs['enclosure']['type']=='application/x-bittorrent')) {
     $links[] = $rs['enclosure']['url'];
  } else {
     if(isset($rs['link'])) {
        $links[] = $rs['link'];
     }
     if(isset($rs['id']) && stristr($rs['id'], 'http://')) { // Atom
        $links[] = $rs['id'];
     }
	 if(isset($rs['enclosure'])) { // RSS Enclosure
        $links[] = $rs['enclosure']['url'];
     }
  }

  if (count($links)==1) {
	$link = $links[0];
	if (stristr("$link", "torcache.net") || stristr("$link", "itorrents.org")){
		$link = magnetlink_getMagnetLinkFromURL($link);
 	}
  } else if (count($links) > 0) {
	$link = choose_torrent_link($links);
  }
  $link = str_replace(" ", "%20", $link);
  return html_entity_decode($link);
}
```
Originally I had the function _magnetlink_getMagnetLinkFromURL($url)_ in its own file and included it to _twxa_feed.php_.

A little side effect is, that immediately after a torrent is added in this way, its title only shows the hash value until the name got resolved by transmission.

Maybe you can improve this in many ways. I hope it helps anyway.

**Comment by dchang0** [comment]
Very cool!
I'll add it in the next release (probably 1.2.0).
Thanks very much!
(I'll leave this ticket open until the feature is added.)

**Comment by dchang0** [comment]
I have some questions, if you don't mind.
I notice that the .torrent file itself that has the hash for the filename does seem to be a valid torrent file. Thus, it should be possible to add it to Transmission without needing the hash for the magnet link.
This raises the question: did you run into a situation where torrentwatch-xa would not add either the magnet link or the torrent file? I'm guessing yes, which led you to write these functions.
If so, then that is a bug I should fix. It should try the magnet link, then if it doesn't find one, **fall back** to the torrent file, then maybe try to determine the hash from the link **if** there is no valid torrent file.

Anyway, I'd like to know more details about how exactly these unusual items failed. I'll add limetorrents.cc to my Feeds and add some Favorites to try to trigger the same problem too. Thanks!

**Comment by dchang0** [comment]
It might be that the link you provided to itorrents.org above goes through CloudFlare. Maybe the redirecting confuses torrentwatch-xa. It does eventually deliver a valid torrent file after several minutes.

**Comment by dchang0** [comment]
Cool--I was able to immediately reproduce the problem. Yeah, I suspect that the real cause is that itorrents.org uses CloudFlare. Give me some time to figure this out. I will have to add a lot of debugging code to make sure the torrent file is being delivered properly and whether the CloudFlare redirect's interstitial page is what's causing the problem.

**Comment by dchang0** [comment]
It does look like CloudFlare is doing some sort of blocking, returning zero bytes of data and apparently closing the connection. I think that it thinks torrentwatch-xa is a bot or spider.

**Comment by efelon** [comment]
You went already way further than me back then. I think to remember something with cloudflare, but my memory doesn't spit out more than that. 

Good luck with it. I hope the effort is not too much and cloudflare is not modifying the method all the time.
Anyway you can use my solution as fallback. ;)

**Comment by dchang0** [comment]
CloudFlare apparently has three requirements:

1. browser must return a User-Agent header
2. browser must support Javascript and run some Javascript provided by the CloudFlare interstitial
3. browser must receive a cookie and then use the cookie to get past the interstitial

There is a 3rd party library here on GitHub called KyranRana/cloudflare-bypass that could do the job. I might use it if it isn't constantly being defeated by CloudFlare. If CloudFlare does keep updating their algorithm to defeat bots, there isn't much reason to participate in the arms race; I would use your method as a fallback.

**Comment by dchang0** [comment]
BTW, rather than check for the domains torcache.net or itorrents.org, I think it may be enough to check for these:

1. $tor is empty/blank
2. SHA-1 hash is in title

This would allow your code to work with any future domain we haven't yet encountered that also uses CloudFlare AND uses the trick of putting the torrent hash in the URL.

**Comment by dchang0** [comment]
I'm finally working on this again. I've decided that I'll add a detector of a hash in the URL that kicks in if the URL returns a zero-length .torrent file. The CloudFlare stuff is just too complicated to build into torrentwatch-xa.

The difference between the method I will use and your great fix is that my changes will occur mostly in client_add_torrent().

**Comment by dchang0** [comment]
The problem has been fixed in 1.2.0. I will test it for a week or two and then commit it.

This fix works for any URL that contains a torrent hash that doesn't return a torrent file. It will get around any site that uses CloudFlare and happens to put the hash in the filename. If the website uses CloudFlare but does not put the hash in the filename, we don't have a way to get around that.

**Comment by dchang0** [comment]
1.2.0 has been tested and posted.

**Comment by efelon** [comment]
Hey dchang0,
just a little note to confirm that 1.2.0 is working with my feeds. Updated yesterday and tested a few.
Thanks for your work.

**Comment by dchang0** [comment]
Thanks for bringing it to my attention, and thanks for reporting on your upgrade!
On 4/30/2019 12:37:52 AM, Martin <notifications@github.com> wrote:
Hey dchang0,
just a little note to confirm that 1.2.0 is working with my feeds. Updated yesterday and tested a few.
Thanks for your work.
